/**
 * writeTraceReport — bundle a session's trace into ONE self-contained HTML file
 * a tester can open and send. Screenshots are embedded as data URIs, so it's a
 * single portable artifact: no folder, no external files, no server.
 *
 * "When it breaks, send me the trace" — this is that trace.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import type { Trace, TraceEntry } from "../types.js";

export async function writeTraceReport(trace: Trace, outPath?: string): Promise<string> {
  const out = path.resolve(outPath ?? path.join(trace.dir, "report.html"));
  const html = await buildHtml(trace);
  await fs.mkdir(path.dirname(out), { recursive: true });
  await fs.writeFile(out, html, "utf8");
  return out;
}

async function buildHtml(trace: Trace): Promise<string> {
  const total = trace.entries.length;
  const failed = trace.entries.filter((e) => !e.ok).length;
  const llm = trace.entries.filter((e) => e.resolvedByLLM).length;
  const lastUrl = [...trace.entries].reverse().find((e) => e.pageUrl)?.pageUrl ?? "";

  const rows: string[] = [];
  for (let i = 0; i < trace.entries.length; i++) {
    rows.push(await renderEntry(trace, i, trace.entries[i]!));
  }

  const rawJson = esc(JSON.stringify(trace, null, 2));

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>doink trace — ${esc(trace.sessionId)}</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body { font-family: "Geist Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    margin: 0; padding: 2rem 1.25rem; line-height: 1.5; color: #16181d; background: #fafafa; }
  @media (prefers-color-scheme: dark) { body { color: #e6e6e6; background: #0e0f12; } }
  .wrap { max-width: 900px; margin: 0 auto; }
  h1 { font-size: 1.1rem; font-weight: 600; margin: 0 0 .25rem; letter-spacing: -0.01em; }
  .sub { opacity: .6; font-size: .8rem; margin-bottom: 1.25rem; }
  .stats { display: flex; gap: 1.25rem; flex-wrap: wrap; font-size: .8rem; margin-bottom: 1.5rem; }
  .stat b { font-weight: 600; } .bad b { color: #d33; }
  .entry { border: 1px solid #0001; border-left-width: 3px; border-radius: 6px;
    padding: .7rem .85rem; margin-bottom: .6rem; background: #fff; }
  @media (prefers-color-scheme: dark) { .entry { background: #16181d; border-color: #fff2; } }
  .entry.ok { border-left-color: #3a8; } .entry.fail { border-left-color: #d33; }
  .head { display: flex; gap: .6rem; align-items: baseline; flex-wrap: wrap; font-size: .82rem; }
  .idx { opacity: .4; min-width: 1.5rem; }
  .act { font-weight: 600; }
  .target { opacity: .8; word-break: break-all; }
  .tag { font-size: .68rem; padding: .05rem .4rem; border-radius: 999px; border: 1px solid #0002; opacity: .8; }
  @media (prefers-color-scheme: dark) { .tag { border-color: #fff3; } }
  .st-ok { color: #2a7; } .st-fail { color: #d33; font-weight: 600; }
  .ms { opacity: .45; margin-left: auto; font-size: .74rem; }
  pre { white-space: pre-wrap; word-break: break-word; font-size: .78rem;
    background: #f2f2f2; padding: .7rem; border-radius: 5px; margin: .6rem 0 0; overflow-x: auto; }
  @media (prefers-color-scheme: dark) { pre { background: #0b0c0e; } }
  img { max-width: 100%; border: 1px solid #0002; border-radius: 5px; margin-top: .6rem; }
  details { margin-top: 2rem; font-size: .8rem; }
  summary { cursor: pointer; opacity: .7; }
  .note { opacity: .55; font-size: .75rem; margin-top: .4rem; }
</style></head>
<body><div class="wrap">
  <h1>doink trace report</h1>
  <div class="sub">${esc(trace.sessionId)} &middot; ${esc(trace.startedAt)}${lastUrl ? " &middot; " + esc(lastUrl) : ""}</div>
  <div class="stats">
    <div class="stat"><b>${total}</b> actions</div>
    <div class="stat ${failed ? "bad" : ""}"><b>${failed}</b> failed</div>
    <div class="stat"><b>${llm}</b> LLM-resolved</div>
  </div>
  ${rows.join("\n")}
  <details><summary>raw trace.json (machine-readable)</summary><pre>${rawJson}</pre></details>
  <div class="note">Generated by doink. This file is self-contained — send it as-is.</div>
</div></body></html>`;
}

async function renderEntry(trace: Trace, i: number, e: TraceEntry): Promise<string> {
  const tags: string[] = [];
  if (e.cached) tags.push(`<span class="tag">cached</span>`);
  else if (e.resolvedByLLM) tags.push(`<span class="tag">llm</span>`);
  if (e.resolvedSelector && e.resolvedSelector !== e.target) {
    tags.push(`<span class="tag">→ ${esc(trunc(e.resolvedSelector, 48))}</span>`);
  }

  let body = "";
  if (!e.ok && e.error) {
    body += `<pre>${esc(e.error.rendered ?? e.error.message)}</pre>`;
    const img = await embedImage(trace, e.screenshotPath);
    if (img) body += `<img alt="failure screenshot" src="${img}"/>`;
  } else if (e.meta && Object.keys(e.meta).length) {
    body += `<div class="note">${esc(compactMeta(e.meta))}</div>`;
  }

  return `<div class="entry ${e.ok ? "ok" : "fail"}">
    <div class="head">
      <span class="idx">${i}</span>
      <span class="act">${esc(e.action)}</span>
      <span class="target">${esc(trunc(e.target, 80))}</span>
      <span class="${e.ok ? "st-ok" : "st-fail"}">${e.ok ? "ok" : "FAIL"}</span>
      ${tags.join(" ")}
      <span class="ms">${e.durationMs}ms</span>
    </div>${body}
  </div>`;
}

async function embedImage(trace: Trace, p?: string): Promise<string | undefined> {
  if (!p) return undefined;
  // Try the recorded path, then the basename within the trace dir (robust to a moved folder).
  for (const cand of [p, path.join(trace.dir, path.basename(p))]) {
    try {
      const buf = await fs.readFile(cand);
      return `data:image/png;base64,${buf.toString("base64")}`;
    } catch {
      /* try next */
    }
  }
  return undefined;
}

function compactMeta(meta: Record<string, unknown>): string {
  const parts: string[] = [];
  for (const [k, v] of Object.entries(meta)) {
    if (v == null) continue;
    const s = typeof v === "object" ? JSON.stringify(v) : String(v);
    parts.push(`${k}: ${trunc(s, 60)}`);
  }
  return parts.join("  ·  ");
}

function trunc(s: string, n: number): string {
  return s.length > n ? s.slice(0, n - 1) + "…" : s;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
